name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.actor != 'lineforge-github-action'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Neovim
        uses: muniftanjim/setup-neovim-action@v1
        with:
          tag: v0.10.0

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Run tests
        run: make test
  docs:
    name: Generate documentation
    runs-on: ubuntu-latest
    if: github.actor != 'lineforge-github-action'
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.LINEFORGE_ACTIONS_APP_ID }}
          private-key: ${{ secrets.LINEFORGE_ACTIONS_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Setup Neovim
        uses: muniftanjim/setup-neovim-action@v1
        with:
          tag: v0.10.0

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Generate docs
        run: make gen_docs

      - name: Commit changes
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            [docgen] Update docs
            skip-checks: true
        run: |
          git config user.name "lineforge-github-action"
          git config user.email "lineforge-github-action@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add README.md doc
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})

  stylua:
    name: Stylua lint
    runs-on: ubuntu-latest
    if: github.actor != 'lineforge-github-action'
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/
